# Copyright (c) PyPTO Contributors.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

"""
Golden script writer for the PyPTO runtime module.

Generates a ``golden.py`` file compatible with Simpler's CodeRunner from a list
of :class:`TensorSpec` objects and a user-supplied golden function.

Generated file format::

    import torch

    __outputs__ = ["out"]
    RTOL = 1e-5
    ATOL = 1e-5

    def generate_inputs(params):
        query = torch.randn((32, 128), dtype=torch.bfloat16)
        out   = torch.zeros((32, 128), dtype=torch.float32)
        return [
            ("query", query),
            ("out", out),
        ]

    def compute_golden(tensors, params):
        tensors["out"][:] = tensors["query"].float().sum(dim=-1, keepdim=True)
"""

import ast
import inspect
import re
import textwrap
from collections.abc import Callable
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import torch  # type: ignore[import]

from .tensor_spec import SCALAR_CTYPE_MAP, ScalarSpec, TensorSpec

_AUTO_IMPORT_LINES = {
    "struct": "import struct",
}


def write_golden(
    tensor_specs: list[TensorSpec],
    golden_fn: Callable,
    output_path: Path,
    rtol: float = 1e-5,
    atol: float = 1e-5,
    scalar_specs: list[ScalarSpec] | None = None,
) -> Path:
    """Generate and write a ``golden.py`` file for Simpler's CodeRunner.

    Args:
        tensor_specs: Ordered list of tensor specifications matching the program's
            parameter list.
        golden_fn: A callable with signature ``(tensors, params)`` that computes
            expected outputs in-place (writes to ``tensors[output_name]``).
        output_path: Destination path for the generated file.
        rtol: Relative tolerance used by CodeRunner for result comparison.
        atol: Absolute tolerance used by CodeRunner for result comparison.
        scalar_specs: Optional list of scalar parameter specifications.  Scalar
            OrchArg entries appear after all tensor entries in the generated list.

    Returns:
        The resolved ``output_path`` after writing.
    """
    content = generate_golden_source(tensor_specs, golden_fn, rtol, atol, scalar_specs=scalar_specs)
    output_path = Path(output_path)
    output_path.write_text(content, encoding="utf-8")
    return output_path


def generate_golden_source(
    tensor_specs: list[TensorSpec],
    golden_fn: Callable | None,
    rtol: float,
    atol: float,
    *,
    compute_golden_src: str | None = None,
    scalar_specs: list[ScalarSpec] | None = None,
) -> str:
    """Build the full content of golden.py as a string.

    Args:
        tensor_specs: Ordered list of tensor specifications.
        golden_fn: A callable whose source is extracted to produce ``compute_golden``.
            Must be provided when *compute_golden_src* is ``None``.
        rtol: Relative tolerance written into the generated file.
        atol: Absolute tolerance written into the generated file.
        compute_golden_src: Pre-extracted ``compute_golden`` function source.
            When provided, *golden_fn* is ignored and this string is used directly.
            Use this when the source comes from a method that requires caller-side
            transformation (e.g. stripping ``self`` from the signature).
        scalar_specs: Optional list of scalar OrchArg specifications.  Entries are
            placed after all tensor entries in the returned list, matching the
            OrchArg slot order produced by orchestration codegen.

    Returns:
        Full Python source for ``golden.py`` as a string.
    """
    scalars = scalar_specs or []
    output_names = [spec.name for spec in tensor_specs if spec.is_output]

    # compute_golden: use caller-supplied source or extract from golden_fn
    if compute_golden_src is None:
        if golden_fn is None:
            raise ValueError("Either golden_fn or compute_golden_src must be provided")
        compute_golden_src = _extract_compute_golden(golden_fn)

    imports = _compute_golden_imports(compute_golden_src)
    if scalars:
        imports.append("import ctypes")
    imports.append("import torch")

    lines: list[str] = [
        '"""',
        "Auto-generated golden script — do not edit by hand.",
        "",
        "Generated by pypto.runtime.golden_writer",
        '"""',
        "",
        *imports,
        "",
        f"__outputs__ = {output_names!r}",
        f"RTOL = {rtol}",
        f"ATOL = {atol}",
        "",
        "def generate_inputs(params):",
        '    """Generate inputs as a list of (name, value) tuples."""',
    ]

    # Tensor variable declarations
    for spec in tensor_specs:
        lines.append(f"    {spec.name} = {_init_expr(spec)}")

    # Scalar variable declarations
    for spec in scalars:
        ctype_ctor = SCALAR_CTYPE_MAP[spec.ctype]
        lines.append(f"    {spec.name} = {ctype_ctor}({spec.value!r})")

    lines.append("")
    lines.append("    return [")
    for spec in tensor_specs:
        lines.append(f'        ("{spec.name}", {spec.name}),')
    for spec in scalars:
        lines.append(f'        ("{spec.name}", {spec.name}),')
    lines.append("    ]")
    lines.append("")
    lines.append("")

    lines.extend(compute_golden_src.splitlines())
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _compute_golden_imports(compute_golden_src: str) -> list[str]:
    """Return import lines required by the generated compute_golden body."""
    return [
        import_line
        for module_name, import_line in _AUTO_IMPORT_LINES.items()
        if re.search(rf"\b{module_name}\.", compute_golden_src)
    ]


def _init_expr(spec: TensorSpec) -> str:
    """Return the Python expression (string) used to initialise this tensor in golden.py."""
    import torch  # type: ignore[import]  # noqa: PLC0415 — optional dependency

    dtype_str = _torch_dtype_str(spec.dtype)
    shape_str = repr(tuple(spec.shape))

    # Outputs are always zero-initialised; their content is set by compute_golden.
    if spec.is_output or spec.init_value is None:
        return f"torch.zeros({shape_str}, dtype={dtype_str})"

    iv = spec.init_value

    if isinstance(iv, (int, float)):
        return f"torch.full({shape_str}, {iv!r}, dtype={dtype_str})"

    if isinstance(iv, torch.Tensor):
        return _tensor_literal_expr(iv, shape_str, dtype_str)

    if callable(iv):
        # Supported torch factory functions can be reproduced literally.
        if iv is torch.randn:
            return f"torch.randn({shape_str}, dtype={dtype_str})"
        if iv is torch.rand:
            return f"torch.rand({shape_str}, dtype={dtype_str})"
        if iv is torch.zeros:
            return f"torch.zeros({shape_str}, dtype={dtype_str})"
        if iv is torch.ones:
            return f"torch.ones({shape_str}, dtype={dtype_str})"
        raise ValueError(
            f"Callable init_value {iv!r} for tensor {spec.name!r} is not supported by "
            "golden_writer. Use a scalar, a torch.Tensor, or one of: "
            "torch.randn, torch.rand, torch.zeros, torch.ones."
        )

    raise TypeError(f"Unsupported init_value type {type(iv)!r} for tensor {spec.name!r}")


def _tensor_literal_expr(tensor: "torch.Tensor", shape_str: str, dtype_str: str) -> str:
    """Generate an inline expression for a concrete torch.Tensor init_value."""
    import torch  # type: ignore[import]  # noqa: PLC0415 — optional dependency

    if tensor.numel() == 0:
        return f"torch.zeros({shape_str}, dtype={dtype_str})"

    # Constant tensor
    if torch.all(tensor == tensor.flatten()[0]):
        val = tensor.flatten()[0].item()
        if val == 0.0:
            return f"torch.zeros({shape_str}, dtype={dtype_str})"
        if val == 1.0:
            return f"torch.ones({shape_str}, dtype={dtype_str})"
        return f"torch.full({shape_str}, {val!r}, dtype={dtype_str})"

    # Identity matrix
    if tensor.ndim == 2 and tensor.shape[0] == tensor.shape[1]:
        if torch.allclose(tensor.float(), torch.eye(tensor.shape[0])):
            return f"torch.eye({tensor.shape[0]}, dtype={dtype_str})"

    # Small tensor: inline list literal
    if tensor.numel() <= 100:
        return f"torch.tensor({tensor.tolist()!r}, dtype={dtype_str})"

    # Large tensor: fall back to zeros with a warning comment
    return (
        f"torch.zeros({shape_str}, dtype={dtype_str})  "
        f"# WARNING: tensor too large ({tensor.numel()} elements) to inline; "
        "replace with actual data."
    )


def _torch_dtype_str(dtype: "torch.dtype") -> str:
    """Return the string representation of a torch dtype (e.g. 'torch.float32')."""
    import torch  # type: ignore[import]  # noqa: PLC0415 — optional dependency

    _map: dict[torch.dtype, str] = {
        torch.float32: "torch.float32",
        torch.float16: "torch.float16",
        torch.bfloat16: "torch.bfloat16",
        torch.float64: "torch.float64",
        torch.int8: "torch.int8",
        torch.int16: "torch.int16",
        torch.int32: "torch.int32",
        torch.int64: "torch.int64",
        torch.bool: "torch.bool",
    }
    result = _map.get(dtype)
    if result is None:
        raise ValueError(f"Unsupported dtype {dtype!r} in TensorSpec")
    return result


def _extract_compute_golden(golden_fn: Callable) -> str:
    """Extract source of *golden_fn* and rename it to ``compute_golden``.

    The resulting string is a properly-indented top-level function definition
    named ``compute_golden`` with the same body as *golden_fn*.

    When *golden_fn* is a bound method (detected via ``inspect.ismethod``), four
    additional transformations are applied, handling both single-line and
    multiline signatures:

    - The ``def name(`` is renamed to ``def compute_golden(``.
    - The ``self`` parameter is stripped (single-line: via regex; multiline: the
      standalone ``self,`` continuation line is dropped).
    - The return type annotation (``-> ...:``) is removed from the closing
      signature line, since ``compute_golden`` in golden.py is untyped.
    - Simple ``self.<attr>`` references in the function body are replaced with
      literal values from the bound instance.

    Args:
        golden_fn: User-provided golden function or bound method.
            Standalone functions must have signature ``(tensors, params)``.
            Bound methods must have signature ``(self, tensors, params)``.

    Returns:
        Source code for ``compute_golden(tensors, params)`` as a string.
    """
    try:
        source = inspect.getsource(golden_fn)
    except (TypeError, OSError) as exc:
        raise RuntimeError(
            f"Cannot extract source code from golden function {golden_fn!r}. "
            "Ensure it is defined in a .py file (not in a REPL or dynamically)."
        ) from exc

    # Remove extra leading indentation (e.g. if defined inside a class or function)
    source = textwrap.dedent(source)

    is_method = inspect.ismethod(golden_fn)
    original_name = golden_fn.__name__
    lines = source.splitlines()
    renamed_lines: list[str] = []
    in_sig = False  # True while still inside a multiline def signature

    for line in lines:
        if not in_sig and line.lstrip().startswith(f"def {original_name}("):
            new_line = line.replace(f"def {original_name}(", "def compute_golden(", 1)
            if is_method:
                # Strip self from the def line: handles "(self, ...)" and "(self,"
                new_line = re.sub(r"\(self,\s*", "(", new_line, count=1)
                new_line = new_line.replace("(self)", "()", 1)
            if new_line.rstrip().endswith(":"):
                # Single-line signature — strip return annotation if present
                if is_method and "->" in new_line:
                    new_line = new_line.split("->")[0].rstrip() + ":"
            else:
                in_sig = True  # Signature continues on subsequent lines
            renamed_lines.append(new_line)
        elif in_sig:
            if is_method and line.strip() in ("self,", "self"):
                continue  # Drop standalone self parameter line
            new_line = line
            if new_line.rstrip().endswith(":"):
                # Last line of a multiline signature
                if is_method and "->" in new_line:
                    new_line = new_line.split("->")[0].rstrip() + ":"
                in_sig = False
            renamed_lines.append(new_line)
        else:
            renamed_lines.append(line)

    source = "\n".join(renamed_lines)
    if is_method:
        source = _inline_bound_self_attributes(source, golden_fn.__self__)
    return source


def _inline_bound_self_attributes(source: str, bound_instance: object) -> str:
    """Replace literal-compatible ``self.<attr>`` references with bound values."""
    attr_names = set(re.findall(r"\bself\.([A-Za-z_][A-Za-z0-9_]*)\b", source))
    for attr_name in sorted(attr_names):
        if not hasattr(bound_instance, attr_name):
            raise RuntimeError(f"Bound golden method references missing attribute self.{attr_name}")

        attr_value = getattr(bound_instance, attr_name)
        literal_value = repr(attr_value)
        try:
            ast.literal_eval(literal_value)
        except (SyntaxError, ValueError) as exc:
            raise RuntimeError(
                "Bound golden method references unsupported non-literal attribute "
                f"self.{attr_name}={attr_value!r}"
            ) from exc

        source = re.sub(rf"\bself\.{attr_name}\b", literal_value, source)

    return source
